# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address_ether',
            field=macaddress.fields.MACAddressField(integer=True, null=True),
        ),
    ]
