# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kb', '0001_initial'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_l567', models.IntegerField(db_index=True, default=-1)),
                ('seq', models.BigIntegerField(db_index=True, default=-1)),
                ('tx_pkts', models.BigIntegerField(default=0)),
                ('tx_bytes', models.BigIntegerField(default=0)),
                ('first_seen', models.DateTimeField(null=True)),
                ('last_seen', models.DateTimeField(auto_now=True, null=True)),
                ('closed_flag', models.BooleanField(default=False)),
                ('syn_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DNScache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_inet', models.GenericIPAddressField(db_index=True)),
                ('name', models.CharField(max_length=253)),
                ('type', models.CharField(max_length=15)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_ether', macaddress.fields.MACAddressField(blank=True, db_index=True, integer=True, null=True)),
                ('address_inet', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('distance', models.IntegerField(default=0)),
                ('protocol_l3', models.IntegerField(default=0)),
                ('tx_pkts', models.BigIntegerField(default=0)),
                ('tx_bytes', models.BigIntegerField(default=0)),
                ('rx_pkts', models.BigIntegerField(default=0)),
                ('rx_bytes', models.BigIntegerField(default=0)),
                ('first_seen', models.DateTimeField(null=True)),
                ('last_seen', models.DateTimeField(auto_now=True, null=True)),
                ('ether_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kb.EtherOUI')),
            ],
        ),
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_inet', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('mask_inet', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('address_bcast', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(db_index=True, default=0)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discovery.Interface')),
                ('protocol_l4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kb.ServiceName')),
                ('service_detec', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='config.Service')),
                ('service_port', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='config.Service')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kb.OperatingSystem')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Site')),
            ],
        ),
        migrations.AddField(
            model_name='net',
            name='gateway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='discovery.System'),
        ),
        migrations.AddField(
            model_name='net',
            name='name_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='discovery.System'),
        ),
        migrations.AddField(
            model_name='net',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Site'),
        ),
        migrations.AddField(
            model_name='interface',
            name='net',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discovery.Net'),
        ),
        migrations.AddField(
            model_name='interface',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Origin'),
        ),
        migrations.AddField(
            model_name='interface',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discovery.System'),
        ),
        migrations.AddField(
            model_name='connection',
            name='dst_socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='discovery.Socket'),
        ),
        migrations.AddField(
            model_name='connection',
            name='src_socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='discovery.Socket'),
        ),
        migrations.AlterUniqueTogether(
            name='socket',
            unique_together=set([('interface', 'port', 'protocol_l4')]),
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together=set([('address_ether', 'address_inet', 'origin')]),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set([('src_socket', 'dst_socket', 'protocol_l567')]),
        ),
    ]
