# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socket',
            name='protocol_l4',
            field=models.IntegerField(default=0),
        ),
    ]
