# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_auto_20160406_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socket',
            name='service_detec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='socket',
            name='service_port',
            field=models.IntegerField(default=0),
        ),
    ]
