# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0014_auto_20151018_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='address_inet',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
