# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0016_auto_20160317_2329'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='port',
            unique_together=set([('interface', 'port', 'proto')]),
        ),
    ]
