# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0017_auto_20160318_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='first_seen',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='first_seen',
            field=models.DateTimeField(null=True),
        ),
    ]
