# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0018_auto_20160318_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='tx_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='connection',
            name='tx_pkts',
            field=models.BigIntegerField(default=0),
        ),
    ]
