# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_sensor'),
        ('discovery', '0020_remove_connection_terminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.Sensor'),
        ),
    ]
