# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0021_interface_sensor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together=set([('address_ether', 'address_inet', 'sensor')]),
        ),
    ]
