# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0022_auto_20160318_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='sensor',
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together=set([('address_ether', 'address_inet')]),
        ),
    ]
