# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20160318_0119'),
        ('discovery', '0023_auto_20160318_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.Sensor'),
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together=set([('address_ether', 'address_inet', 'sensor')]),
        ),
    ]
