# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0024_auto_20160318_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Sensor'),
        ),
    ]
