# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0025_auto_20160318_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='sensor',
            new_name='sensors',
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together=set([('address_ether', 'address_inet', 'sensors')]),
        ),
    ]
