# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0026_auto_20160318_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='sensors',
            new_name='sensor',
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together=set([('address_ether', 'address_inet', 'sensor')]),
        ),
    ]
